pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Image') {
            steps {
                script {
                    // Build the Docker image and fail the build if there are any errors
                    sh 'docker build --no-cache -t pingurl:latest .'
                }
            }
        }

        stage('Lint') {
            steps {
                script {
                    // Run pylint and fail if the score is under 9.0 (we are currently at ~9.5)
                    def pylintStatus = sh(script: 'docker run --rm pingurl:latest pylint --fail-under=9.0 /backend', returnStatus: true)
                    if (pylintStatus != 0) {
                        error("Pylint score is below the threshold of 9.0")
                    }
                }
            }
        }
        
        stage('Stop Existing Container') {
            steps {
                script {
                    // Stop and remove the Docker container if it's running
                    sh 'docker stop pingapp || true'
                    sh 'docker rm pingapp || true'
                }
            }
        }

        stage('Run Application') {
            steps {
                script {
                    // Run the Flask application in a Docker container
                    sh 'docker run -d -p 5000:5000 --name pingapp pingurl:latest'
                }
            }
        }
    }

    post {
        //always {
        //    // Clean up: Stop and remove the Docker container if it's running
        //    sh 'docker stop pingapp || true'
        //    sh 'docker rm pingapp || true'
        //}
        failure {
            echo 'The build failed.'
            // Clean up
            sh 'docker stop pingapp || true'
            sh 'docker rm pingapp || true'
        }
    }
}
