pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    // Build the latest image of 'pingurl'
                    docker.build("pingurl:latest")
                }
            }
        }

        stage('Linting') {
            steps {
                // Run Pylint
                script {
                    docker.image('pingurl:latest').inside {
                        sh './backend/app.py'
                    }
                }
            }
            post {
                failure {
                    // Actions to be taken if the linting stage fails
                    echo 'Linting issues detected. Failing the build.'
                    error('Linting issues detected')
                }
            }
        }

        stage('Run Docker') {
            steps {
                script {
                    // Define your Docker-related steps here
                    docker.image('pingurl:latest').run()
                    // Additional Docker steps
                }
            }
        }
    }
}
