name: Docker Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build --no-cache -t pingurl:latest .

      - name: Run pytest
        run: docker run --rm pingurl:latest pytest /backend

      - name: Run Application
        run: |
          docker run --rm -d -p 5000:5000 --name pingapp pingurl:latest
          sleep 5
          if [ "$(docker inspect -f '{{.State.Running}}' pingapp)" != "true" ]; then
              echo "Error: The application failed to start."
              exit 1
          fi
          docker stop pingapp
